# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 05:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_on', models.DateTimeField()),
                ('status', models.CharField(choices=[('NQ', 'No Quotation'), ('AR', 'Awaiting Confirmation'), ('CO', 'Confirmed')], max_length=2)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=1000)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InquiryEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment')),
                ('inquiry', models.ManyToManyField(to='rental.Inquiry')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PA', 'Accepted'), ('RE', 'Rejected'), ('AW', 'Awaiting Confirmation')], max_length=2)),
                ('created_on', models.DateTimeField()),
                ('transportation_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comments', models.CharField(max_length=1000)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rental.Inquiry')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment')),
                ('inquiry', models.ManyToManyField(to='rental.Quotation')),
            ],
        ),
    ]
