# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-21 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('AQ', 'Awaiting Quotation'), ('AR', 'Awaiting Confirmation'), ('CO', 'Confirmed')], max_length=2),
        ),
    ]
