# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-22 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiryequipment',
            name='inquiry',
        ),
        migrations.AddField(
            model_name='inquiryequipment',
            name='inquiry',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rental.Inquiry'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='quotationequipment',
            name='inquiry',
        ),
        migrations.AddField(
            model_name='quotationequipment',
            name='inquiry',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rental.Inquiry'),
            preserve_default=False,
        ),
    ]
