# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_auto_20170726_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='comments',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
