# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_auto_20170726_0749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='created_on',
            new_name='sent_on',
        ),
    ]
