# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(default='../static/images/defaultequipment.png', upload_to='equipmentimages'),
        ),
    ]
