# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-22 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='hours_worked',
            field=models.IntegerField(default=0),
        ),
    ]
