# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-22 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_hours_worked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancetransaction',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancetransaction',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
