# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_auto_20170711_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.ImageField(default='../media/equipmentimages/defaultequipment.png', upload_to='equipmentimages/'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('EX', 'Excavator'), ('BL', 'Backhoe Loader'), ('BR', 'Breaker'), ('SL', 'Skidsteer Loader'), ('RR', 'Road Roller'), ('RG', 'Road Grader'), ('PL', 'Payloader'), ('BD', 'Bulldozer'), ('CR', 'Crane'), ('AC', 'Air Compressor'), ('GS', 'Genarating Sets'), ('FL', 'Forklifts'), ('FT', 'Flatbed Trucks'), ('DT', 'Dump Truck'), ('LB', 'Low Bed Trailer'), ('PM', 'Prime Mover'), ('MT', 'Manlift Trucks'), ('MC', 'Motorcycles'), ('OT', 'Other')], max_length=2),
        ),
    ]
