# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_auto_20170711_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.ImageField(default='../media/equipmentimages/defaultequipment.png', upload_to='equipmentimages'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('IE', 'In Engagement'), ('AV', 'Available'), ('UM', 'Under Maintenance'), ('US', 'Unserviceable')], max_length=2),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('AC', 'Air Compressor'), ('BL', 'Backhoe Loader'), ('BR', 'Breaker'), ('BD', 'Bulldozer'), ('CR', 'Crane'), ('DT', 'Dump Truck'), ('EX', 'Excavator'), ('FT', 'Flatbed Trucks'), ('FL', 'Forklifts'), ('GS', 'Genarating Sets'), ('LB', 'Low Bed Trailer'), ('MT', 'Manlift Trucks'), ('MC', 'Motorcycles'), ('PL', 'Payloader'), ('PM', 'Prime Mover'), ('RG', 'Road Grader'), ('RR', 'Road Roller'), ('SL', 'Skidsteer Loader'), ('OT', 'Other')], max_length=2),
        ),
    ]
