# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_auto_20170711_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('AC', 'Air Compressor'), ('BL', 'Backhoe Loader'), ('BR', 'Breaker'), ('BD', 'Bulldozer'), ('CR', 'Crane'), ('DT', 'Dump Truck'), ('EX', 'Excavator'), ('FT', 'Flatbed Truck'), ('FL', 'Forklifts'), ('GS', 'Genarating Set'), ('LB', 'Low Bed Trailer'), ('MT', 'Manlift Truck'), ('MC', 'Motorcycle'), ('PL', 'Payloader'), ('PM', 'Prime Mover'), ('RG', 'Road Grader'), ('RR', 'Road Roller'), ('SL', 'Skidsteer Loader'), ('OT', 'Other')], max_length=2),
        ),
    ]
