# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-21 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_type',
            field=models.CharField(choices=[('FI', 'Finance'), ('EM', 'Equipment Manager'), ('MM', 'Maintenance Manager'), ('CU', 'Customer')], max_length=2),
        ),
    ]
